java_test(
  name = 'tests',
  srcs = glob([
    '*.java',
  ]),
  runtime_deps = [
    '//external:hamcrest',
  ],
  deps = [
    '//external:guava',
    '//external:junit',
    '//external:truth',
    "//java/reagera",
  ]
)
